# Generated by Django 5.1.1 on 2024-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardowner',
            name='card_uid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cardowner',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
